package runtime

func dashboardHTML() string {
	return `<!doctype html><html><head><title>vibe-proxy</title><style>
body{margin:0;background:#08090a;color:#f4f4f5;font-family:Inter,ui-sans-serif,system-ui}.wrap{max-width:1120px;margin:48px auto;padding:24px}.card{border:1px solid #27272a;background:#111113;border-radius:18px;padding:24px;margin-bottom:16px}.muted{color:#a1a1aa}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.mono,input,select,textarea{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}.row{display:flex;gap:12px;margin:10px 0}.row>*{flex:1}input,select,textarea{background:#18181b;color:#f4f4f5;border:1px solid #3f3f46;border-radius:10px;padding:10px}button{background:#f4f4f5;color:#09090b;border:0;border-radius:10px;padding:10px 14px;font-weight:700;cursor:pointer}.secondary{background:#27272a;color:#f4f4f5}.ok{color:#22c55e}.err{color:#ef4444}pre{white-space:pre-wrap;background:#18181b;border:1px solid #27272a;border-radius:12px;padding:12px;max-height:320px;overflow:auto}</style></head><body><main class="wrap"><section class="card"><p class="muted">vibe-proxy local</p><h1>Agent-first LLM protocol switcher</h1><p class="muted">Configure providers locally, then use stable OpenAI/Anthropic endpoints.</p><div class="grid"><div><b>OpenAI Chat</b><p class="mono">/v1/chat/completions</p></div><div><b>OpenAI Responses</b><p class="mono">/v1/responses</p></div><div><b>Anthropic</b><p class="mono">/anthropic/v1/messages</p></div></div></section>
<section class="card"><h2>Admin</h2><div class="row"><input id="adminToken" placeholder="Admin token, e.g. admin-token"><button onclick="saveToken()">Save token</button><button class="secondary" onclick="loadSnapshot()">Refresh</button></div><p class="muted">Token is stored only in this browser's localStorage.</p></section>
<section class="card"><h2>Add Provider</h2><div class="row"><input id="providerId" value="newapi" placeholder="Provider ID"><select id="providerType"><option value="openai-compatible">OpenAI-compatible</option><option value="anthropic">Anthropic</option></select></div><div class="row"><input id="baseUrl" value="http://host.docker.internal:3000/v1" placeholder="Base URL"><input id="apiKeyEnv" value="NEW_API_KEY" placeholder="API key env var"></div><div class="row"><input id="models" value="deepseek-v4-flash,gpt-5.4-mini" placeholder="Models, comma separated"><input id="alias" value="vibe-chat" placeholder="Alias"><input id="aliasModel" value="deepseek-v4-flash" placeholder="Alias target model"></div><div class="row"><input id="defaultModel" value="vibe-chat" placeholder="Default model"><button onclick="configureProvider()">Save & reload</button><button class="secondary" onclick="testProvider()">Test provider</button></div><p class="muted">Secrets are referenced by environment variable. Start Docker with <span class="mono">NEW_API_KEY=...</span>; the UI does not store the key itself.</p></section>
<section class="card"><h2>Runtime</h2><pre id="output">Click Refresh.</pre></section>
<script>
const out = document.getElementById('output');
const token = localStorage.getItem('vibe_admin_token') || '';
document.getElementById('adminToken').value = token;
function saveToken(){ localStorage.setItem('vibe_admin_token', document.getElementById('adminToken').value); out.textContent='Saved admin token locally.'; }
function headers(){ const t=document.getElementById('adminToken').value; return {'Content-Type':'application/json','Authorization':'Bearer '+t}; }
async function show(resp){ const text=await resp.text(); try{ out.textContent=JSON.stringify(JSON.parse(text),null,2); }catch{ out.textContent=text; } }
async function loadSnapshot(){ await show(await fetch('/admin/config/snapshot',{headers:headers()})); }
async function configureProvider(){ const payload={id:providerId.value,type:providerType.value,base_url:baseUrl.value,api_key_env:apiKeyEnv.value,models:models.value.split(',').map(s=>s.trim()).filter(Boolean),alias:alias.value,alias_model:aliasModel.value,default_model:defaultModel.value}; await show(await fetch('/admin/local/configure',{method:'POST',headers:headers(),body:JSON.stringify(payload)})); }
async function testProvider(){ await show(await fetch('/admin/providers/test?id='+encodeURIComponent(providerId.value),{method:'POST',headers:headers()})); }
loadSnapshot().catch(()=>{});
</script></main></body></html>`
}
